# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
  export ZSH="/home/jintain/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
#ZSH_THEME="robbyrussell"
#ZSH_THEME="agnoster"
#ZSH_THEME="oxide"
ZSH_THEME="geoffgarside"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  autojump
)
. /usr/share/autojump/autojump.sh

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
#

export PATH=/usr/local/cuda-9.0/bin:$PATH:/usr/local/go/bin
export LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64:$LD_LIBRARY_PATH

export CMAKE_PREFIX_PATH="$CMAKE_PREFIX_PATH:/usr/local/include/eigen3/cmake:/media/jintain/sg/ai/career/robot/ctirobot/learn/torchcpp/libtorch/share/cmake"

alias work="cd /media/jintain/sg"
alias work2="cd /media/jintain/sg/ai/career/robot/ctirobot"
alias work3="cd /media/jintain/wd"
alias work4="cd /media/jintain/wd/ai/career/robot/ctirobot"
#source /opt/ros/melodic/setup.zsh
#alias rm='rm -i'
alias todo="gedit ~/.todo.txt"


CAFFE_ROOT="/home/jintain/caffe/python"

export LIBTORCH_ROOT="/media/jintain/sg/ai/career/robot/ctirobot/fruits/3d_det/second_pytorch/spconv/libtorch"

alias clion=/opt/clion-2018.3.3/bin/clion.sh
export PYTHONPATH=$PYTHONPATH:/media/jintain/sg/ai/career/robot/ctirobot/milestones/avod_ssd/wavedata/:/media/jintain/sg/ai/career/robot/ctirobot/milestones/second_pytorch:${CAFFE_ROOT}


alias kiss="source /opt/ros/melodic/setup.zsh"
alias kiss2="source /opt/ros/crystal/setup.zsh"

alias initreal="source /media/jintain/wd/ros/fusion/catkin_ws_realsense/devel/setup.zsh"
#export PATH="/home/jintain/miniconda3/bin:$PATH"

export APOLLO_HOME=/media/jintain/sg/ai/career/robot/ctirobot/vendor/apollo

alias cloud-ss='ssh root@47.106.163.216'
export NUMBAPRO_CUDA_DRIVER=/usr/lib/x86_64-linux-gnu/libcuda.so
export NUMBAPRO_NVVM=/usr/local/cuda/nvvm/lib64/libnvvm.so
export NUMBAPRO_LIBDEVICE=/usr/local/cuda/nvvm/libdevice



export CPATH=$CPATH:/usr/local/lib/python3.6/dist-packages/tensorflow/include/external/local_config_cuda/cuda/cuda/


alias nu="nautilus ."

export TURTLEBOT3_MODEL=burger
export CITYSCAPES_DATASET=/media/jintain/sg/permanent/datasets/Cityscapes


alias goland="/opt/GoLand-2018.3.2/bin/goland.sh"

alias tryit="cd /media/jintain/wd/weapons/tryit"
#export CPLUS_INCLUDE_PATH="/media/jintain/sg/ai/products/yolov3_mobilenet_caffe/include":/usr/local/cuda/include

PATH="/home/jintain/perl5/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="/home/jintain/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/home/jintain/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/home/jintain/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/jintain/perl5"; export PERL_MM_OPT;

eval $(thefuck --alias)
