# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=/Users/jintian/.oh-my-zsh

export TF_CPP_MIN_LOG_LEVEL=2

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
# plugins=(git autojump)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
export PATH=$PATH:/usr/local/mysql/bin

alias cloud-ruixun="ssh root@47.106.162.124"

alias cloud-furong="ssh jinfagang@39.108.130.161"
alias cloud-139="ssh ubuntu@139.199.158.201"
alias cloud-119="ssh ubuntu@119.29.67.126"
alias cloud-ali="ssh root@112.74.76.245"
alias pool="cd /Volumes/Disk2/CodeSpace/Pool"

alias cloud-daige="ssh -Y jintian@192.168.191.205"
alias cloud-home="ssh -Y jintian@192.168.191.1"
alias cloud-nlp="ssh -Y nlp@192.168.191.234"
alias blog="cd /Volumes/xs/docs/blogs"
alias work="cd /Volumes/xs/lans"


alias typora="open -a typora"
alias dl="cd /Volumes/Disk2/SafariDownloads/"
#alias blog="cd /Volumes/Disk2/"
alias psql-start="pg_ctl -D /usr/local/var/postgres -l logfile start"


alias go=colorgo
export PYTHONPATH=$PYTHONPATH:/usr/local/bin/python3.6

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

export GOPATH="$HOME/go"
export PATH="$GOPATH/bin:$PATH"
alias netac="cd /Volumes/xs/lans"
alias work2="cd /Volumes/Netac/lans"

alias amazon="ssh -i "~/Desktop/TestOnAWSKey.pem" ubuntu@ec2-34-229-82-205.compute-1.amazonaws.com"

alias term="open -a Terminal.app"
export ANDROID_DAILY_OVERRIDE="f45e5d17ca3a0975c45e7dc90a57fc060946b744"
export PATH="/usr/local/sbin:$PATH"

alias book="cd /Volumes/xs/Documents/Books"
alias cloud-sia="ssh root@106.14.174.108"

export LANG=en_US.UTF-8
alias reminder="cd /Volumes/xs/docs/reminder&& typora ."



# both for macOS and Ubuntu
export CMAKE_PREFIX_PATH="$CMAKE_PREFIX_PATH:/usr/local/include/eigen3/cmake"

. /$HOME/z.sh

